import type { AiClient } from './types.js';
import type { Article } from '../sources/types.js';

export async function generateArticle(
  article: Article,
  client: AiClient,
  tone: string
): Promise<string> {
  const today = new Date().toISOString().split('T')[0];

  const primarySourceInfo = article.primarySourceUrl
    ? `一次ソース: ${article.primarySourceUrl}（種別: ${article.primarySourceType ?? 'unknown'}）`
    : '一次ソース: なし';

  const contentSection = article.content
    ? `本文:\n${article.content.slice(0, 2000)}`
    : article.summary
    ? `サマリー:\n${article.summary}`
    : '本文・サマリーなし';

  const toneInstruction = tone === 'technical'
    ? 'テクニカルな解説調で、専門用語を正確に使いながら詳しく説明してください。'
    : tone === 'casual'
    ? 'カジュアルで読みやすいトーンで、難しい用語は噛み砕いて説明してください。'
    : `${tone}のトーンで記事を作成してください。`;

  const systemPrompt = `あなたは海外AI情報を日本語でわかりやすく解説する技術ライターです。
${toneInstruction}

以下の厳密なMarkdown構造で出力してください（この形式から外れないこと）:

# タイトル（日本語訳）

> **3行サマリー**
> - （1行目）
> - （2行目）
> - （3行目）

## 概要
（2-3段落で概要を説明）

## ポイント
- （箇条書きで重要ポイントを3-5件）

## 解説
（詳細な解説を3-5段落）

---

## ソース
- 📄 一次情報: [タイトル](URL)（種別）
- 📰 参照記事: [タイトル](URL)

Generated by Mimi | ${today}`;

  const userPrompt = `以下の記事を日本語解説記事に変換してください。

タイトル: ${article.title}
URL: ${article.url}
${primarySourceInfo}
${contentSection}`;

  return client.chat(systemPrompt, userPrompt);
}
